# Dependencies
markdown: redcarpet

redcarpet:
    extensions:
        - no_intra_emphasis
        - fenced_code_blocks
        - autolink
        - tables
        - strikethrough
        - superscript
        - smart
        - space_after_headers
        - footnotes
        - underline

highlighter: pygments

# Permalinks
permalink: /:title

# Server
source: docs
host: 0.0.0.0
destination: _gh_pages
port: 4000
baseurl: /vip
url: http://samzeng.com/
encoding: UTF-8

# Custom vars
current_version: 0.0.1
repo: https://github.com/samzeng/vip
